cors:
  originPatterns: "*"
spring:
  application:
    name: "Voz Cidadã"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/voz-cidada
    username: postgres
    password: ${POSTGRES_PASSWORD:admin}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  security:
    oauth2:
      client:
        registration:
          google.client-id: ${GOOGLE_CLIENT_ID}
          google.scope:
            - profile
            - email
springdoc:
  swagger-ui:
    url: /openapi.yml
logging:
  level:
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: OFF
security:
  token:
    secret: ${JWT_SECRET:default-secret}
    expire-length: 3600
server:
  port: 5000
app:
  upload:
    dir: "/app/uploads"
