cors:
  originPatterns: https://localhost:8080,http://localhost:5173
spring:
  application:
    name: "Voz Cidadã"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/voz-cidada
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  security:
    oauth2:
      client:
        registration:
          google.client-id: 518788781560-5kjacjm9okd3cnofcs2beq2e6nb7br12.apps.googleusercontent.com
          google.scope:
            - profile
            - email
springdoc:
  swagger-ui:
    url: /openapi.yml
logging:
  level:
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: OFF
security:
  token:
    secret: ${JWT_SECRET:default-secret}
    expire-length: 3600
server:
  port: 8080
app:
  upload:
    dir: "/app/uploads"